import { Urbanist } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

// Load the Urbanist font with selected weights and subsets
const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"], // Add any weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-slate-900 text-slate-100">
      {/* Use urbanist.className to apply the font */}
      <body className={urbanist.className}>
        <Header />
        {children}
        <div className="h-[500vh]"></div>
      </body>
    </html>
  );
}
